replicaCount: 2

image:
  repository: chandana1712/taxi-app
  tag: "1.0.1"
  pullPolicy: Always

imagePullSecrets:
  name: docker-cred
  dockerconfigjson: ""

service:
  type: LoadBalancer
  port: 8000

namespace: taxi-app
